#!/bin/sh
while getopts i:n:c:b opt; do
  case $opt in
    'i') icon=":$OPTARG:" ;;
    'n') name=$OPTARG ;;
    'c') channel=$OPTARG ;;
    'b') back_quote="on" ;;
    *) exit 1 ;;
  esac
done

shift $((OPTIND - 1))

url=${1:?urlを指定してください！！}
shift 1

message="$(printf %q "$(echo "${*:-$(cat -)}")")"

json="$(cat <<EOF
payload={
  "channel": "${channel:-trash}",
  "username": "${name:-my_bot}",
  "icon_emoji": "${icon:-":ghost:"}",
  "text": "$([ "$back_quote" != "on" ] && echo "$message" || echo '```'"$message" '```')"
}
EOF)"

curl -sfm5 -XPOST --data-urlencode "$json" $url 
